export enum STATUS_COLORS {
  COLOR_APPOINTMENT_PENDING_HEADER = '#D9D9D9',
  COLOR_APPOINTMENT_PENDING_TEXT = '#111827',
  COLOR_APPOINTMENT_PENDING_BACKGROUND = '#FFFFFF',
  COLOR_APPOINTMENT_PENDING_HEADER_CARD = '#989898',
}
